---
- hosts: all
  become_user: root
  become: yes
  vars: 
    APP_MESSAGE: "HELLO WORLD"
  tasks:
    - debug:
        msg: Hello, world
    
    - name: Install docker and python-docker-py
      ansible.builtin.yum:
        name: ['docker','python-docker-py']
        state: present
     
        
    - name: Copy myapp service script
      ansible.builtin.copy:
        src: myapp.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0755

    - name: Enable myapp service with systemd
      ansible.builtin.systemd:
        name: myapp.service
        enabled: yes
        daemon_reload: yes 

  
    # Goal: While status of docker is not yet alive, keep checking status
    - name: Display message about docker starting
      debug: msg="Waiting for docker to start..."
    
   ## Another way to check docker status, but we will prefer the service module
   # - name: Wait until docker status is running
   #   ansible.builtin.command: 'systemctl status --quiet docker'
   #   register: check_docker_service
   #   until: check_docker_service is succeeded

    - name: Wait for docker service
      service:
        name: docker
        state: started
      register: docker_service
      until: docker_service.status.ActiveState == "active"
      retries: 2
      delay: 1  

  
    - name: Create folder /tmp/build_app
      ansible.builtin.file:
         path: /tmp/build_app
         state: directory
         mode: 0755
      tags: create_buildapp_folder

    - name: Copy app files into /tmp/build_app
      ansible.builtin.copy:
         src: app/
         dest: /tmp/build_app/
         

    - name: Replace APP_MESSAGE in main.py script
      ansible.builtin.replace:
        path: /tmp/build_app/main.py
        regexp: 'APP_MESSAGE'
        replace: '{{ APP_MESSAGE }}'
      tags: update_py_script

    - name: Copy Dockerfile to /tmp/build_app
      ansible.builtin.copy:
        src: app/Dockerfile
        dest: /tmp/build_app/Dockerfile
        owner: root
        mode: 0644

    - name: Build the docker app
      docker_image:
        name: myapp
        build:
          path: /tmp/build_app
        source: build
        
    - name: Start the app
      ansible.builtin.service:
        name: myapp
        state: started
      register: app_start

    - name: Check status of app
      command: "systemctl status --quiet myapp"
      register: check_myapp
      when: app_start is succeeded

  # Might have needed to define an selinux context here

    - name: Test the app with curl to port 8000
      ansible.builtin.uri:
        url: http://localhost:8000
      register: check_uri

    - name: Show success if app responds
      debug: msg="App is working on port 8000, it works!  {{ check_uri }}"
      when: check_uri is succeeded
      ignore_errors: true

    - name: Show fail if app does not respond
      debug: msg="App is not responding on port 8000"
      when: check_uri is failed     

    
