---
- hosts: all
  become_user: root
  become: yes
  vars: 
    APP_MESSAGE: "HELLO WORLD"
  tasks:
    - debug:
        msg: Hello, world
    
    - name: Install docker and python-docker-py
      ansible.builtin.yum:
        name: ['docker','python-docker-py']
        state: present
     
        
    - name: Copy myapp service script
      ansible.builtin.copy:
        src: myapp.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0755

    - name: Enable myapp service with systemd
      ansible.builtin.systemd:
        name: myapp.service
        enabled: yes
        daemon_reload: yes 


    - name: Start docker service
      service:
        name: docker
        state: started
      register: start_docker_service
      #until: start_docker_service.status.ActiveState == "active"
    

# Another way, but does not seem to get updated facts after it runs once
#   - name: Get service_facts
#     ansible.builtin.service_facts:
#     register: get_facts
#
#   - name: Display fact for docker service status
#     debug:
#       var: ansible_facts.services["docker.service"]  
#     until: '"running" in ansible_facts.services["docker.service"]'
#     retries: 1
#      delay: 1
  
    # Goal: While status of docker is not yet alive, keep checking status
    - name: Display message about docker starting
      debug: msg="Waiting for docker to start..."
    
    - name: Wait for docker service to be confirmed
      command: "systemctl status --quiet docker"
      register: check_docker_service
      until: check_docker_service is succeeded

   
      

    - name: Create folder /tmp/build_app
      ansible.builtin.file:
         path: /tmp/build_app
         state: directory
         mode: 0755
      tags: create_buildapp_folder

    - name: Copy app files into /tmp/build_app
      ansible.builtin.copy:
         src: app/
         dest: /tmp/build_app/
         

    - name: Replace APP_MESSAGE in main.py script
      ansible.builtin.replace:
        path: /tmp/build_app/main.py
        regexp: 'APP_MESSAGE'
        replace: '"{{ APP_MESSAGE }}"'
      tags: update_py_script

    - name: Copy Dockerfile to /tmp/build_app
      ansible.builtin.copy:
        src: app/Dockerfile
        dest: /tmp/build_app/Dockerfile
        owner: root
        mode: 0644

    - name: Build the docker app
      docker_image:
        name: myapp
        build:
          path: /tmp/build_app
        source: build
        
    - name: Start the app
      ansible.builtin.service:
        name: myapp
        state: started
      register: app_start

    - name: Check status of app
      command: "systemctl status --quiet myapp"
      register: check_myapp
      when: app_start is succeeded
    
